#! /bin/bash

docker kill skullcollector
docker rm skullcollector
truncate ./logs/* --size 0

docker run -d -v $(pwd)/logs:/var/log/supervisor -p 80:80 -p 9200:9200 -p 443:443 -p 514:514/udp -p 8125:8125/udp -p 8126:8126 --name skullcollector mikemackintosh/skullcollector
